### ISSUE TITLE
v0.12.6 fails to compile on CentOS 6.8 "expected initializer before ‘stop’"

### ISSUE THREAD

**Issue by IyadKandalaft** [RcppCore/Rcpp#539]
CRAN source package v0.12.6 fails to compile on CentOS 6.8 but v0.12.5 compiles fine.  

```

* installing *source* package ‘Rcpp’ ...
** package ‘Rcpp’ successfully unpacked and MD5 sums checked
** libs
g++ -I/opt/R/R3/3.1.3/lib64/R/include -DNDEBUG -I../inst/include/ -I/usr/local/include    -fpic  -g -O2  -c Date.cpp -o Date.o
In file included from ../inst/include/RcppCommon.h:122,
                 from ../inst/include/Rcpp.h:27,
                 from Date.cpp:31:
../inst/include/Rcpp/exceptions.h:267: error: expected initializer before ‘stop’
../inst/include/Rcpp/exceptions.h:272: error: expected initializer before ‘stop’
../inst/include/Rcpp/exceptions.h:277: error: expected initializer before ‘stop’
../inst/include/Rcpp/exceptions.h:282: error: expected initializer before ‘stop’
../inst/include/Rcpp/exceptions.h:287: error: expected initializer before ‘stop’
../inst/include/Rcpp/exceptions.h:292: error: expected initializer before ‘stop’
../inst/include/Rcpp/exceptions.h:297: error: expected initializer before ‘stop’
../inst/include/Rcpp/exceptions.h:302: error: expected initializer before ‘stop’
../inst/include/Rcpp/exceptions.h:307: error: expected initializer before ‘stop’
../inst/include/Rcpp/exceptions.h:312: error: expected initializer before ‘stop’
../inst/include/Rcpp/exceptions.h:317: error: expected initializer before ‘stop’
In file included from ../inst/include/Rcpp/Vector.h:56,
                 from ../inst/include/Rcpp.h:38,
                 from Date.cpp:31:
../inst/include/Rcpp/utils/tinyformat.h: In member function ‘Rcpp::internal::DimNameProxy& Rcpp::internal::DimNameProxy::assign(SEXPREC*)’:
../inst/include/Rcpp/utils/tinyformat.h:127: error: too many arguments to function ‘void Rcpp::stop(const std::string&)’
../inst/include/Rcpp/vector/DimNameProxy.h:43: error: at this point in file
In file included from ../inst/include/Rcpp.h:47,
                 from Date.cpp:31:
../inst/include/Rcpp/utils/tinyformat.h: In constructor ‘Rcpp::Function_Impl<StoragePolicy>::Function_Impl(const std::string&, const std::string&)’:
../inst/include/Rcpp/utils/tinyformat.h:127: error: too many arguments to function ‘void Rcpp::stop(const std::string&)’
../inst/include/Rcpp/Function.h:72: error: at this point in file
make: *** [Date.o] Error 1
ERROR: compilation failed for package ‘Rcpp’
* removing ‘/home/vagrant/R/x86_64-unknown-linux-gnu-library/3.1/Rcpp’
* restoring previous ‘/home/vagrant/R/x86_64-unknown-linux-gnu-library/3.1/Rcpp’

The downloaded source packages are in
	‘/tmp/RtmpaYpuI9/downloaded_packages’
Warning message:
In install.packages("Rcpp") :
  installation of package ‘Rcpp’ had non-zero exit status
> 
> 
```

**Comment by eddelbuettel** [comment]
Please look at issue #538 which I just closed 5 minutes ago.

**Comment by eddelbuettel** [comment]
For reference, this is discussed in #512 (with reference to the drat repo), #516, #519, #520 and now #538.   

You want these two commits if you do it by hand:  
- a2e45fa5a3e95125938f3865a661e42c00877900, 
- 3dea272cbd9e243ccf771ee8d23f1dd3af2a08e4

My recommendation, however, is to use [the Rcpp drat repo](http://rcppcore.github.io/drat/) to access the interim release 0.12.6.1 which is just the trusted 0.12.6 plus the fix to make it build on outdated R versions such as R 3.0.* or 3.1.*
