### ISSUE TITLE
use of overloaded operator '=' is ambiguous 

### ISSUE THREAD

**Issue by piccolbo** [RcppCore/Rcpp#133]
Hi, this is new as of 0.11.1, compiles fine with 0.11.0

Error is

```
typed-bytes.cpp:264:18: error: use of overloaded operator '=' is ambiguous (with operand types 'RObject' (aka 'RObject_Impl<PreserveStorage>') and 'List' (aka 'Vector<19>'))
      new_object = unserialize_list(data, start);
      ~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Library/Frameworks/R.framework/Versions/3.0/Resources/library/Rcpp/include/Rcpp/RObject.h:35:9: note: candidate function
        RCPP_GENERATE_CTOR_ASSIGN(RObject_Impl) 
        ^
/Library/Frameworks/R.framework/Versions/3.0/Resources/library/Rcpp/include/Rcpp/macros/interface.h:23:80: note: expanded from macro 'RCPP_GENERATE_CTOR_ASSIGN'
typedef AttributeProxyPolicy<__CLASS__> AttributePolicy ;                      \
                                                                               ^
/Library/Frameworks/R.framework/Versions/3.0/Resources/library/Rcpp/include/Rcpp/macros/interface.h:30:12: note: expanded from macro '\
RCPP_CTOR_ASSIGN'
__CLASS__& operator=(const __CLASS__& rhs) {                                   \
           ^
/Library/Frameworks/R.framework/Versions/3.0/Resources/library/Rcpp/include/Rcpp/RObject.h:49:23: note: candidate function
        RObject_Impl& operator=( SEXP other ){
                      ^
```

Function `unserialize_list` returns a `List`, `new_object` is an `RObject`. Reproduce with 
`install_github("rmr2", "RevolutionAnalytics", subdir="pkg", ref = "3.0.0")` (I may have to use a workaround in master, so please use that tag). I tried to create a minimalistic example but no luck. I thought this should fail in the same way

```
 cppFunction(code = "RObject f(List l) {RObject o = l; return o;}")
```

But it compiles and works.  `unserialize_list` is not overloaded so I don't see the difference with the above. Thanks.
