### ISSUE TITLE
Unable to compile packages with Rcpp 0.11.0 on Windows

### ISSUE THREAD

**Issue by dakep** [RcppCore/Rcpp#115]
Hi,

since Rcpp 0.11.0 I'm unable to compile a package that links to Rcpp on Windows 7 with Rtools30 and Rtools31 (R version 3.0.2).

I've created a very simple package (http://rotinaj.org/pub/CompileTest_1.0.tar.gz; it is basically the skeleton created by R Studio) that throws the error:

```
PS C:\Users\David\Desktop> R.exe CMD INSTALL --build .\CompileTest_1.0.tar.gz
* installing to library 'c:/R/R-3.0.2/library'
* installing *source* package 'CompileTest' ...
** libs

*** arch - i386
cygwin warning:
  MS-DOS style path detected: c:/R/R-3.0.2/etc/i386/Makeconf
  Preferred POSIX equivalent is: /cygdrive/c/R/R-3.0.2/etc/i386/Makeconf
  CYGWIN environment variable option "nodosfilewarning" turns off this warning.
  Consult the user's guide for more details about POSIX paths:
    http://cygwin.com/cygwin-ug-net/using.html#using-pathnames
g++ -m32 -I"c:/R/R-3.0.2/include" -DNDEBUG    -I"c:/R/R-3.0.2/library/Rcpp/include" -I"d:/RCompile/CRANpkg/extralibs64/l
ocal/include"     -O2 -Wall  -mtune=core2 -c CompileTest.cpp -o CompileTest.o
g++ -m32 -shared -s -static-libgcc -o CompileTest.dll tmp.def CompileTest.o  -Ld:/RCompile/CRANpkg/extralibs64/local/lib
/i386 -Ld:/RCompile/CRANpkg/extralibs64/local/lib -Lc:/R/R-3.0.2/bin/i386 -lR
g++.exe: error: : No such file or directory
ERROR: compilation failed for package 'CompileTest'
* removing 'c:/R/R-3.0.2/library/CompileTest'
```

I couldn't find the reason why g++ gives the error
**g++.exe: error: : No such file or directory**

The package compiles fine with Rcpp 0.10.\* and on Mac OS 10.9 with Rcpp 0.11.0.

Best regards,
David
