### ISSUE TITLE
Possible bug in Rcpp::export

### ISSUE THREAD

**Issue by samuel-rosa** [RcppCore/Rcpp#719]
After updating Rcpp from 0.12.10 to 0.12.11, Rcpp::export seems not to support the modification of the name of an exported function. In fact, it appears to export methods using both the alternate name and the name of the C++ function. The following piece of code was extracted from `src/RcppExports.cpp`.

```
RcppExport SEXP spsann_objMSSDCpp(SEXP);
RcppExport SEXP spsann_spJitterCpp(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
RcppExport SEXP spsann_updateMSSDCpp(SEXP, SEXP, SEXP, SEXP);
RcppExport SEXP spsann_updatePPLCpp(SEXP, SEXP, SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"spsann_.objMSSD", (DL_FUNC) &spsann_.objMSSD, 1},
    {"spsann_.spJitterCpp", (DL_FUNC) &spsann_.spJitterCpp, 7},
    {"spsann_.updateMSSDCpp", (DL_FUNC) &spsann_.updateMSSDCpp, 4},
    {"spsann_.updatePPLCpp", (DL_FUNC) &spsann_.updatePPLCpp, 3},
    {"spsann_objMSSDCpp",    (DL_FUNC) &spsann_objMSSDCpp,    1},
    {"spsann_spJitterCpp",   (DL_FUNC) &spsann_spJitterCpp,   7},
    {"spsann_updateMSSDCpp", (DL_FUNC) &spsann_updateMSSDCpp, 4},
    {"spsann_updatePPLCpp",  (DL_FUNC) &spsann_updatePPLCpp,  3},
    {NULL, NULL, 0}
};
```
The alternate names are those that start with a `.`. When building the package (`spsann`), the following error message is issued for the lines containing the alternate names:

`'spsann_' was not declared in this scope`. 

Every one of the files in `src` containing  c++ functions start with the following:

```
#include <Rcpp.h>
using namespace Rcpp;

// [[Rcpp::export(".alternate_name")]]
```

Source code of the  `spsann` package is available at https://github.com/samuel-rosa/spsann.

Please let me know if you need more information.

**Comment by jjallaire** [comment]
This is fixed on master (just install from GitHub or Drat)

**Comment by eddelbuettel** [comment]
As @jjallaire said, already fixed (and already reported as #702, fixed in #703).  Please see [this message to rcpp-devel](http://lists.r-forge.r-project.org/pipermail/rcpp-devel/2017-June/009602.html) for details.
