### PR TITLE
Inline `Rcpp_list6()`

### LINKED ISSUE #1048: Rcpp uses `Rf_list6()`, which was added around R 3.4
Rcpp 1.0.4 no longer builds from source on R 3.3 because of a call to `Rf_list6()` that was added here:

https://github.com/RcppCore/Rcpp/commit/d65f3c08148b0de1254f833077a154d21e9aa1c0#diff-c524021f4c8787893aa50c251e4c35d7R35

That is because `list6()` was added to R in this commit here, around R 3.4

https://github.com/wch/r-source/commit/7199ea1d53538c55e4ca51a993ec2a394dd63a1f#diff-b2ce19943acaccf93558f770778c4730

Compilation on R 3.3 gives:

```cpp
* installing *source* package ‘Rcpp’ ...
** package ‘Rcpp’ successfully unpacked and MD5 sums checked
** libs
g++ -I/opt/R/3.2.5/lib/R/include -DNDEBUG -I../inst/include/ -I/usr/local/include    -fpic  -g -O2  -c api.cpp -o api.o
In file included from ../inst/include/RcppCommon.h:135:0,
                 from ../inst/include/Rcpp.h:27,
                 from api.cpp:24:
../inst/include/Rcpp/lang.h: In function ‘SEXPREC* Rcpp::Rcpp_list7(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP)’:
../inst/include/Rcpp/lang.h:45:55: error: ‘Rf_list6’ was not declared in this scope
     x0 = Rf_cons(x0, Rcpp_list6(x1, x2, x3, x4, x5, x6));
                                                       ^
../inst/include/Rcpp/lang.h: In function ‘SEXPREC* Rcpp::Rcpp_lang7(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP)’:
../inst/include/Rcpp/lang.h:53:56: error: ‘Rf_list6’ was not declared in this scope
     x0 = Rf_lcons(x0, Rcpp_list6(x1, x2, x3, x4, x5, x6));
                                                        ^
make: *** [api.o] Error 1
/opt/R/3.2.5/lib/R/etc/Makeconf:143: recipe for target 'api.o' failed
ERROR: compilation failed for package ‘Rcpp’
```

Rcpp could manually add `list6()` like purrr does 
https://github.com/tidyverse/purrr/blob/aa7bc7f6d9854a1f2d5869536af652322a4bf38b/src/utils.c#L29-L34

### PR DESCRIPTION
**Pull request by DavisVaughan**
Closes #1048

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Thanks.  I can assume you tested this R 3.3.* ?   (I have some Docker containers here so I could spot check locally too.)

I am wondering if we should protect the `inline` para with a `#define`.

**Comment by DavisVaughan** [comment]
Yea, here is a {yardstick} build that previously failed, but now relies on this PR. Rcpp builds fine on an R 3.3.* build (and 3.2.*).

https://github.com/tidymodels/yardstick/runs/514069086?check_suite_focus=true#step:8:97

**Comment by eddelbuettel** [comment]
"We apologize for any invoncenience caused."   Always sorry about breakage but hey, it was your colleague :sunglasses: and we did ask for extensive pre-release tests.  But I know how it goes -- CRAN releases just matter more.
